apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 25565
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
